name: First trial
on: 
  push:
    branches: "main"
jobs:
   first-job:
     runs-on: ubuntu-latest
     steps:
     - name: Print greetings
       run: echo "Hellow World"
     - name: Print goodbye
       run: echo "bye,bye"
     - name: Two command
       run: |
            echo "My name is bhushan"
            echo "Tjis is my first GA job"
            uname -a 
   second-job:
       runs-on: ubuntu-latest
       needs: first-job
       steps:
       - name: git version
         run: git --version
       - name: touch file
         run: touch t1 t2 |ls 
