name: Build & Push to GAR

on:
  workflow_dispatch:
    inputs:
      SERVICE:
        description: "Select your service"
        type: choice
        required: true
        options:
          - F1ChatGpt
          - F1Queryv1
          - F1PromptToVideo
          - F1SpeechToText
          - F1SemanticSearch
          - F1TextToSpeech
          - F1CodeGenPT
          - F1Interpreter
          - F1VisualQA
          - F1DataVisualization
          - F1ImageToText
          - F1TextToImage
          - F1ImageGen
          - F1ryzeUI
          - F1ryze2UI
          - F1ryze3UI
          - F1EnterpriseSearch
          - F1PromptStickGen
          - IFLIchatbotapi   # Add your service here
          - F1Productrecommend
          - F1PowerPointGraphGen
          - F1ProposalGeneration
          - F1PropertyInfoExtractor
          - F1PriceComparisonChecker

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Generate Image Name
      run: |
        IMAGE_NAME="${{ github.event.inputs.SERVICE }}"
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

    - name: Extract Version from Branch + Date
      run: |
        RAW_BRANCH="${GITHUB_REF#refs/heads/}"
        PART1=$(echo $RAW_BRANCH | cut -d'/' -f1)
        PART2=$(echo $RAW_BRANCH | cut -d'/' -f2)
        DATE=$(date +'%Y%m%d')
        VERSION="v${PART1}-${PART2}-${DATE}"
        echo "IMAGE_VERSION=$VERSION" >> $GITHUB_ENV

    - name: Auth to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker
      run: gcloud auth configure-docker ${{ secrets.GAR_REGION }}-docker.pkg.dev --quiet

    - name: Build Image
      run: |
        cd $IMAGE_NAME/api
        docker build -t $IMAGE_NAME:$IMAGE_VERSION .

    - name: Tag Image
      run: |
        GAR_IMAGE="${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/ryze-artifact-registry/$IMAGE_NAME/$IMAGE_NAME:$IMAGE_VERSION"
        echo "GAR_IMAGE=$GAR_IMAGE" >> $GITHUB_ENV
        docker tag $IMAGE_NAME:$IMAGE_VERSION $GAR_IMAGE

    - name: Push to GAR
      run: docker push $GAR_IMAGE
